/*
    Project Overview:
        This script performs a comprehensive Exploratory Data Analysis (EDA) on a retail Data Warehouse (Gold Layer). 
        It is designed to validate data integrity, understand business dimensions, 
        and calculate Key Performance Indicators (KPIs).
    
    The analysis follows a logical flow: 
        Metadata Exploration -> Dimensional Profiling -> Metric Aggregation -> Magnitude Analysis.
*/

-- DATABASE EXPLORATION
-- =====================================

-- Explore all objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- Explore all Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS;

	-- For specific Table
	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'dim_customers';

-- DIMENSIONS EXPLORATION
-- =====================================

-- Explore all the Countries our customer come from
SELECT DISTINCT country
FROM gold.dim_customers;

-- Explore all Categories "The Major Divisions"
SELECT DISTINCT category, subcategory, product_name
FROM gold.dim_products
ORDER BY 1,2,3;

-- DATE EXPLORATION i.e checking boundaries
-- =====================================
-- Find date of first and last order, years of sales available
SELECT 
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	DATEDIFF(YEAR,MIN(order_date),MAX(order_date)) AS order_range_years	-- Datediff accepts only one value, be it year or month or day
FROM gold.fact_sales;

-- Find the youngest and oldest customer
SELECT 
	MIN(birthdate) AS youngest_customer,
	MAX(birthdate) AS oldest_customer
FROM gold.dim_customers


-- MEASURES EXPLORATION i.e calculate the key metric of business (Big Numbers)
						-- Highest Level of Aggregation | Lowest Level of Details 
-- =====================================

-- Find the Total Sales
SELECT SUM(sales) AS total_sales FROM gold.fact_sales;

-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales;

-- Find the average selling price
SELECT AVG(price) AS average_price FROM gold.fact_sales;

-- Find the total number of Orders
SELECT COUNT(order_number) AS total_orders FROM gold.fact_sales;
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales;	-- some customers order multiple times in same order

-- Find the total number of Products
SELECT COUNT(product_key) AS total_products FROM gold.dim_products;

-- Find the total number of Customers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers;

-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.fact_sales;

-- Generate a Report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales) AS measure_report FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_report FROM gold.fact_sales
UNION ALL 
SELECT 'Average Price' AS measure_name, AVG(price) AS measure_report FROM gold.fact_sales
UNION ALL
SELECT 'Total No. Orders' AS measure_name, COUNT(DISTINCT order_number) AS measure_report FROM gold.fact_sales
UNION ALL
SELECT 'Total No. Products' AS measure_name, COUNT(DISTINCT product_key) AS measure_report FROM gold.dim_products
UNION ALL
SELECT 'Total No. Customers' AS measure_name, COUNT(DISTINCT customer_key) AS measure_report FROM gold.dim_customers
UNION ALL
SELECT 'Customers who Ordered' AS measure_name, COUNT(DISTINCT customer_key) AS measure_report FROM gold.fact_sales;

/* MAGNITUDE EXPLORATION  - comparint the measure values by categories
						  - it helps us understand the importance of different categories
*/
-- =========================================================================

-- Find total customers by countries
SELECT
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT 
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- what is the average costs in each category
SELECT
	category,
	AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC;

-- what is the total revenue generated for each category
SELECT
	p.category,
	SUM(f.sales) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- find total revenue generated by each customer
SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC;

-- what is the distribution of sold items across countries
SELECT
	c.country,
	SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY
	c.country
ORDER BY total_sold_items DESC; 

-- RANKINGS
-- =====================================

-- Which 5 products generate the highest revenue
SELECT TOP 5
	p.product_name,
	SUM(f.sales) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- OR

SELECT TOP 5
    p.product_name,
    SUM(f.sales) AS total_revenue
FROM gold.dim_products p
INNER JOIN gold.fact_sales f -- Changed to INNER JOIN
    ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- 5 worst performing products in terms of sales

SELECT TOP 5
	p.product_name,
	SUM(f.sales) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC;
-- OR
SELECT *
FROM
(SELECT TOP 5
	p.product_name,
	SUM(f.sales) total_revenue,
	ROW_NUMBER() OVER (ORDER BY SUM(f.sales) DESC) AS rank_products
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name) t
WHERE rank_products <= 5;

-- FIND TOP 10 CUSTOMERS WHO HAVE GENERATED THE HIGHEST REVENUE
SELECT TOP 10
    c.customer_key,
    CONCAT(c.first_name, ' ', c.last_name) AS full_name,
    SUM(f.sales) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    CONCAT(c.first_name, ' ', c.last_name)
ORDER BY total_revenue DESC;

-- 3 customers with fewest orders placed
SELECT TOP 3
    c.customer_key,
    c.first_name,
	c.last_name,
    COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
	c.last_name
ORDER BY total_orders ASC;